name: Publish PowerShell Module

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.NUGETAPIKEY }}
        shell: pwsh
        run: |
          Publish-Module -Path .\SimplePSLog -NuGetApiKey $env:NUGET_KEY -Verbose